---
name: 'Setup Nimble environment'
description: 'Setup a Nimble environment and add it to the PATH'
author: 'jmgomez'

inputs:
  nimble-version:
    description: >-
      The Nimble version to download (if necessary)
      and use. Examples: '0.16.3', 'stable'
    default: 'stable'
    required: false
  nimble-install-directory:
    description: >-
      The Nimble installation directory.
    default: '.nimble_runtime'
    required: false
  parent-nimble-install-directory:
    description: >-
      The Nimble installation parent directory.
      It will be placed in the current directory if this parameter is empty.
    default: ''
    required: false
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install nimble
      shell: bash
      run: |
        "${{ github.action_path }}/install_nimble.sh" \
          --nimble-version "${{ inputs.nimble-version }}" \
          --parent-nimble-install-directory "${{ inputs.parent-nimble-install-directory }}" \
          --nimble-install-directory "${{ inputs.nimble-install-directory }}" \
          --os "${{ runner.os }}" \
          --repo-token "${{ inputs.repo-token }}"

    - name: Set PATH for Unix
      shell: bash
      run: |
        parent="${{ inputs.parent-nimble-install-directory }}"
        if [[ "${parent}" = "" ]]; then
          parent="$PWD"
        fi
        echo "$parent/${{ inputs.nimble-install-directory }}/bin" >> "$GITHUB_PATH"
      if: runner.os != 'Windows'

    - name: Set PATH for Windows
      shell: pwsh
      run: |
        $parent = "${{ inputs.parent-nimble-install-directory }}"
        if ($parent -eq "") {
          $parent = "$Pwd"
        }
        echo "$parent\${{ inputs.nimble-install-directory }}\bin" >> $Env:GITHUB_PATH
      if: runner.os == 'Windows'

    - name: Print nimble directory
      shell: bash
      run: |
        echo "installed nimble fullpath: $(which nimble)"

    - name: Print nimble version
      shell: bash
      run: nimble -v
