name: build

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '*.md'

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  test:
    runs-on: ${{ matrix.os }}
    needs: before
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        version:
          - 1.0.0
          - stable
          - devel
        exclude:
          - os: macOS-latest
            version: devel
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          nim-version: ${{ matrix.version }}

      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Run build test
        run: nimble install -Y nimjson
      - name: Run command
        run: nimjson -h

  test_v1:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v1
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble
      - uses: jiro4989/setup-nim-action@v1

      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Run build test
        run: nimble install -Y nimjson
      - name: Run command
        run: nimjson -h

  test_devel_latest:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v1

      # Set cache key
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(date "+%Y-%m-%d")"
        shell: bash

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-devel-latest-${{ steps.get-date.outputs.date }}
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-devel-latest
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'devel --latest'

      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Run build test
        run: nimble install -Y nimjson
      - name: Run command
        run: nimjson -h

