name: test_versioning

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  test_vX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-v2
          restore-keys: |
            ${{ runner.os }}-nimble-v2

      - uses: jiro4989/setup-nim-action@cb1fc1270b117457dd0d9f610ec981fad3369cec # v2.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Run build test
        run: nimble install -Y nimjson
      - name: Run command
        run: nimjson -h
